import Head from "next/head";

import TopHeader from "@/component/TopHeader";
import MainPage from "@/component/MainPage";
import Solutions from "@/component/Solutions";
import Features from "@/component/Features";
import { payattitude } from "@/public/ICON";

export default function Home() {
  return (
    <>
      <Head>
        <title>PAYATTITUDE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="" href={payattitude} /> */}
      </Head>
      <TopHeader />
      <MainPage />
      <Solutions />
      <Features />
    </>
  );
}
