export const merchants = [
  {
    no: 1,
    location: "IMAGINE FASHION AND ACCESSORIES",
    address: "111 ALLEN AVENUE IKEJA LAGOS",
    state: "LAGOS",
  },
  {
    no: 2,
    location: "PARTY PERFECT",
    address: "SHOP 40, THE PALMS SHOPPING MALL, LEKKI, LAGOS",
    state: "LAGOS",
  },
  {
    no: 3,
    location: "	EXOTIC INTERIOR DECORATION",
    address: "89 OGUNLANA DRIVE, SURULERE",
    state: "LAGOS",
  },
  {
    no: 4,
    location: "BEAUTIFUL THINGS ACCESSORIES",
    address: "ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 5,
    location: "SOUTHERN DELICACIES LIMITED",
    address: "115 OGUNLANA DRIVE SURULERE",
    state: "LAGOS",
  },
  {
    no: 6,
    location: "GENUSS INVESTMENT LIMITED",
    address: "13 ADEPELE STREET, COMPUTER VILLAGE, IKEJA",
    state: "LAGOS",
  },
  {
    no: 7,
    location: "	BEAUTIFUL THINGS ACCESSORIES",
    address: "11, ADEBOYE SOLANKE STREET, OFF ALLEN AVENUE, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 8,
    location: "KYUTIS CLINIC",
    address: "2A RAYMOND NJOKU STREET, IKOYI",
    state: "LAGOS",
  },
  {
    no: 9,
    location: "PENDERIE VENTURE",
    address: "284 HERBERT MACAULEY WAY YABA",
    state: "LAGOS",
  },
  {
    no: 10,
    location: "	HOMEGATE NIGERIA LIMITED",
    address: "PLOT 6 OBAFEMI OSOBA CRESCENT LEKKI PHASE 1",
    state: "LAGOS",
  },
  {
    no: 11,
    location: "LADY BUTCHER",
    address: "58 Adeniyi Jones Avenue, Ikeja",
    state: "LAGOS",
  },
  {
    no: 12,
    location: "THE MARTHAS PHARMACY",
    address: "	38A AJE ROAD, SABO YABA",
    state: "LAGOS",
  },
  {
    no: 13,
    location: "	SCHOOL KITS LIMITED",
    address: "	64B FOLA OSIBO LEKKI PHASE 1",
    state: "LAGOS",
  },
  {
    no: 14,
    location: "	XPRESS IMAGE COMPANY",
    address: "	20B ELSIE FEMI PEARSE, VICTORIA ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 15,
    location: "PLANET NAILS BEAUTY DIST NIG LTD",
    address: "144 OGUNLANA DRIVE, SURULERE",
    state: "LAGOS",
  },
  {
    no: 16,
    location: "	SOUTHERN DELICACIES",
    address: "	115 OGUNLANA DRIVE SURULERE",
    state: "LAGOS",
  },
  {
    no: 17,
    location: "EXQUISITE RUMORS LIMITED",
    address: "15A, ODUDUWA WAY, GRA, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 18,
    location: "MIDAS TOUCH DRYCLEANERS",
    address: "	61, ALLEN AVENUE, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 19,
    location: "BOCHEPHARM NIGERIA LIMITED",
    address: "41B IWAYA ROAD, YABA",
    state: "LAGOS",
  },
  {
    no: 20,
    location: "BRICAM SCHOOL SERVICES ENTERPRISES",
    address: "3 BABATUNDE DABIRI STREET, LEKKI PHASE 1",
    state: "LAGOS",
  },
  {
    no: 21,
    location: "SITAWELL PHARMACY AND STORES LIMITED",
    address: "	 84 ADENIRAN OGUNSANYA,SURULERE",
    state: "LAGOS",
  },
  {
    no: 22,
    location: "	FUZEB VENTURES",
    address: "12 SAKA TINUBU STREET,VICTORIA ISLAND",
    state: "LAGOS",
  },
  {
    no: 23,
    location: "OASIS SUPERMARKET LIMITED",
    address: "10, TIAMIYU SALVAGE, VICTORIA ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 24,
    location: "RELIANCE ROYAL SUITES LIMITED",
    address: "19-21 MAJEKODUNMI STREET OFF ALLEN AVENUE IKEJA",
    state: "LAGOS",
  },
  {
    no: 25,
    location: "	OOH LA LA FOODS  NIG. LTD",
    address: "FOOD COURT ADENIRAN OGUNSANYA SHOPRITE MALL SURULERE",
    state: "LAGOS",
  },
  {
    no: 26,
    location: "AVALON HOMES AND GIFT ENTERPRISES",
    address: "2 WALE OLATEJU CRESCENT, , LEKKI II, LAGOS",
    state: "LAGOS",
  },
  {
    no: 27,
    location: "MJ TARGET COLLECTIONS LTD",
    address: "51 AWOLOWO WAY, IKEJA",
    state: "LAGOS",
  },
  {
    no: 28,
    location: "CUBANA LIMITED",
    address: "17 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 29,
    location: "CHOPAHOLICS KITCHENS",
    address: "	12, ROAD 1 LEKKI COUNTY , LEKKI, LAGOS",
    state: "LAGOS",
  },
  {
    no: 30,
    location: "MIDAS TOUCH DRYCLEANERS LIMITED",
    address: "35E AJIRAN ROAD, AGUNGI, LEKKI",
    state: "LAGOS",
  },
  {
    no: 31,
    location: "DEVICE PRO SYSTEMS LIMITED",
    address: "14 OREMEJI STREET,COMPUTER VILLAGE,IKEJA",
    state: "LAGOS",
  },
  {
    no: 32,
    location: "EXOTIC INTERIOR DECORATION",
    address: "89 OGUNLANA DRIVE, SURULERE",
    state: "LAGOS",
  },
  {
    no: 33,
    location: "DEVICEPRO SYSTEMS LIMITED",
    address: "13 ADEPELE STREET, COMPUTER VILLAGE, IKEJA",
    state: "LAGOS",
  },
  {
    no: 34,
    location: "	LIFEBIFEBACK PHARMACY AND STORES LTD",
    address: "36 OLD YABA ROAD, EBUTE META OFF HARBERT MACAULY",
    state: "LAGOS",
  },
  {
    no: 35,
    location: "	ALPHAMOGA KIDS PLACE",
    address: "	15A, IKOSI ROAD, OREGUN, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 36,
    location: "COSNET SYSTEMS NIG LTD",
    address: "8 ADETOLA STREET,AGUDA,SURULERE",
    state: "LAGOS",
  },
  {
    no: 37,
    location: "	COSNET SYSTEMS NIG LTD",
    address: "27 ADENIRAN OGUNSANYA STREET,SURULERE",
    state: "LAGOS",
  },
  {
    no: 38,
    location: "TOTAL NIGERIA PLC",
    address: "	KM 16 LEKKI-EKE EXPRESSWAY, AGUNG",
    state: "LAGOS",
  },
  {
    no: 39,
    location: "OFOEGBU ENTERPRISES",
    address: "	10 ONIKOYI STREET,AGUDA,SURULERE",
    state: "LAGOS",
  },
  {
    no: 40,
    location: "MIRIAN GUEST HOUSE",
    address: "27 YESUFU SANUSI STREET, OFF ADENIRAN OGUNSANYA, SURULERE",
    state: "LAGOS",
  },
  {
    no: 41,
    location: "ODL TELECOMMUNICATIONS LTD",
    address: "81 BODE THOMAS STREET,SURULERE",
    state: "LAGOS",
  },
  {
    no: 42,
    location: "	REMILEIMU VENTURES",
    address: "25 MONTGOMERY ROAD YABA",
    state: "LAGOS",
  },
  {
    no: 43,
    location: "	MEGALAG COMPANY LIMITED",
    address: "1 CHIEF NATUFE STREET, SURULERE, LAGOS",
    state: "LAGOS",
  },
  {
    no: 44,
    location: "JEJAJOO",
    address: "2, IKOSI ROAD BY OLUYOLE BUSSTOP, OREGUN, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 45,
    location: "GENUSS INVESTMENT LTD",
    address: "	13 ADEPELE STREET, COMPUTER VILLAGE, IKEJA",
    state: "LAGOS",
  },
  {
    no: 46,
    location: "KIDDING AROUND CONCEPTS",
    address: "	2 AJAYI STREET, ONIKE-IWAYA ROAD, YABA",
    state: "LAGOS",
  },
  {
    no: 47,
    location: "	CHIEFOO SUPERMARKET",
    address: "	8, OLADIMEJI STREET AGUDA SURULERE LAGOS",
    state: "LAGOS",
  },
  {
    no: 48,
    location: "CONCIERGE BUSINESS ENTERPRISE",
    address: "17 ADEOLA ODEKU STREET, VICTORIA ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 49,
    location: "	GNC LIVEWELL LIMITED",
    address: "1B, OPEBI ROAD, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 50,
    location: "OBELE KITCHEN",
    address: "42, IJEDE ROAD, BESIDE MUKAZ PETROL STATION, IKORODU, LAGOS",
    state: "LAGOS",
  },
  {
    no: 51,
    location: "BISMID COSMETICS",
    address: "	62 BANK OLEMOH STREET, AKERELE ROAD, SURULERE, LAGOS",
    state: "LAGOS",
  },
  {
    no: 52,
    location: "	BEAUTIFUL THINGS ACCESSORIES",
    address: "ADMIRALTY WAY LEKKI (BEAUTIFUL THINGS ACCESSORIES)",
    state: "LAGOS",
  },
  {
    no: 53,
    location: "DUFRY DUTY FREE LIMITED",
    address: "Muritala Mohammed International Airport Ikeja Lagos",
    state: "LAGOS",
  },
  {
    no: 54,
    location: "SAVE A LOT SUPERMARKET",
    address: "43 IJEDE ROAD ITAMAGA,IKORODU",
    state: "LAGOS",
  },
  {
    no: 55,
    location: "	T. T. ROBINSON PHARMACEUTICALS",
    address: "	79 ODONLA ROAD, ODOGUNYAN, IKORODU",
    state: "LAGOS",
  },
  {
    no: 56,
    location: "ROYAL BLUES EVENTS AND HOTELS",
    address: "KM 40,LEKKI EPE AWOYAYA IBEJU LEKKI",
    state: "LAGOS",
  },
  {
    no: 57,
    location: "SOCIETY FOR CORPORATE GOVERNANCE NIGERIA LTD/GTE",
    address: "5B LAWANI ODULOYE STREET, ONIRU, VICTORIA ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 58,
    location: "SALAM MOBILE",
    address: "OTUNLA IBEJU-LEKKI, LAGOS",
    state: "LAGOS",
  },
  {
    no: 59,
    location: "BROOK CHERITH LTD",
    address: "	9 ALHAJI KANKE CLOSE, AWOLOWO ROAD, IKOYI",
    state: "LAGOS",
  },
  {
    no: 60,
    location: "AVALON HOMES AND GIFT ENTERPRISES",
    address: "BOLA AHMED TINUBU ROAD, BOGIJE, IBEJU-LEKKI",
    state: "LAGOS",
  },
  {
    no: 61,
    location: "	AJAFAT CONCEPT",
    address: "	2 ALAO SEMIU STREET,IGBE LAARA OFF IJEDE,IKORODU",
    state: "LAGOS",
  },
  {
    no: 62,
    location: "	BEVEFORT PHARMACEUTICAL LTD",
    address: "PLOT 13, SANYAOLU STREET, OREGUN, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 63,
    location: "TRANSMSSION",
    address: "6, ROAD C, UNITY ESTATE OREYO, IKORODU, LAGOS STATE",
    state: "LAGOS",
  },
  {
    no: 64,
    location: "GNC LIVEWELL LIMITED",
    address: "IKEJA CITY MALL, SECOND ENTRANCE",
    state: "LAGOS",
  },
  {
    no: 65,
    location: "DMAYOR GLOBAL VENTURE",
    address: "	1 TIJANI SAKA STREET,IGBO OLUMU,AGRIC,IKORODU",
    state: "LAGOS",
  },
  {
    no: 66,
    location: "DEVICE PRO SYSTEMS LIMITED",
    address:
      "	15A, OMORINRE JOHNSON STREET, OFF BUSOLA DUROSIMI, ETTA, LEKKI PHASE 1, LAGOS STATE",
    state: "LAGOS",
  },
  {
    no: 67,
    location: "	STANDARD ALLIANCE",
    address: "150 LAGOS ROAD, IKORODU",
    state: "LAGOS",
  },
  {
    no: 68,
    location: "THANX SUPERMART",
    address: "10 OLUFEMI ROAD OFF OGUNLANA DRIVE, SURULERE",
    state: "LAGOS",
  },
  {
    no: 69,
    location: "	DEMIONSREATION MINISTRY",
    address:
      "	11/13 SIMBI STREET, OFF AGEGE MOTOR ROAD BY SHOGUNLE BUS-STOP, OSHODI, LAGOS STATE",
    state: "LAGOS",
  },
  {
    no: 70,
    location: "	ZAKONE ENTERPRISES",
    address: "9/11 KUDIRAT ABIOLA WAY, OREGUN, IKEJA",
    state: "LAGOS",
  },
  {
    no: 71,
    location: "GLORIOUS OPPORTUNITY NIGERIA LIMITED",
    address: "G AND M PLACE, ELESHIN BUS STOP, IJEDE ROAD, IKORODU",
    state: "LAGOS",
  },
  {
    no: 72,
    location: "ESSTEE CHUKS ENTERPRISES",
    address: "	12 AYANGBUREN ROAD, IKORODU",
    state: "LAGOS",
  },
  {
    no: 73,
    location: "ABIOLA ASOOKE NIG",
    address: "15 AKINSEMOYIN STREET,OFF BODE THOMAS SURULERE",
    state: "LAGOS",
  },
  {
    no: 74,
    location: "FREEWAY PRIME AUTO LIMITED",
    address: "	KM 47 LEKKI-EPE EXPRESSWAY, AGUNGI",
    state: "LAGOS",
  },
  {
    no: 75,
    location: "	FEDMAND.NAILS",
    address: "ROAD 11, 5 WOLE ARIYO , LEKKI",
    state: "LAGOS",
  },
  {
    no: 76,
    location: "JOBES UNIQUE CORP LIMITED",
    address: "33, NBC ROAD, EBUTE IKORODU,  IKORODU. LAGOS",
    state: "LAGOS",
  },
  {
    no: 77,
    location: "	MULTI SPORTS SER AND ENTERT LTD",
    address:
      "2 ADAMU ORISHA OFF GBAJUMO CLOSE CLOSE ADENIRAN OGUNSANYA STREET,SURULERE",
    state: "LAGOS",
  },
  {
    no: 78,
    location: "	EVAKISTAMEL",
    address:
      "38, AYANBODE STREET,OFF MODUPE BUS STOP, AJAYI ROAD, OGBA IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 79,
    location: "MIDEY'S WORLD",
    address: "97 OBAFEMI AWOLOWO WAY IGBOGBO-BAYEKUN OFIN JUNCTION IKORODU",
    state: "LAGOS",
  },
  {
    no: 80,
    location: "	EVELYN AKENEMA",
    address: "7 AKPOGUMA STREET, KILO BUS/STOP, SURULERE",
    state: "LAGOS",
  },
  {
    no: 81,
    location: "MATILDA MICHAELS LIMITED",
    address: "72 FEMI AYNTUGA CRESCENT, SURULERE",
    state: "LAGOS",
  },
  {
    no: 82,
    location: "NAPMATRONICS AUTO WORKSHOP",
    address: "KM 42 LEKKI EPE EXPRESSWAY ELUJU IBEJU LEKKI",
    state: "LAGOS",
  },
  {
    no: 83,
    location: "NELOS CHILDREN CORNER",
    address: "	SHOP 1 AND 2, BLOCK C AGUDA MARKET, SURULERE",
    state: "LAGOS",
  },
  {
    no: 84,
    location: "EXCELLENT BAR",
    address: "16, MOWOKEKERE BUSSTOP, IJEDE ROAD, IKORODU, LAGOS",
    state: "LAGOS",
  },
  {
    no: 85,
    location: "	MIDELEE AGENCY",
    address:
      "18 MUYIDEEN AGBAKU STREET CAR WASH BUS STOP ELESHIN,IJEDE,IKORODU",
    state: "LAGOS",
  },
  {
    no: 86,
    location: "	NABEEL COMMUNICATION",
    address: "	SHOP 3 ASHELA BUS STOP ,IGBE LAARA,IKORODU",
    state: "LAGOS",
  },
  {
    no: 87,
    location: "	AKINSOLA RAHMON AKINKUNMI (ARKSOF ICT VENTURES)",
    address: "58 AJEGUNLE ROAD,ITA-OLUWO,IKORODU",
    state: "LAGOS",
  },
  {
    no: 88,
    location: "COUNTRY FOOD ENTERPRISES",
    address: "1 OSAPA ROAD, OSAPA, LEKKI",
    state: "LAGOS",
  },
  {
    no: 89,
    location: "	OPRAH NELSONIG",
    address: "3 TESSY STREET, AJIRAN, AGUNGI, LEKKI",
    state: "LAGOS",
  },
  {
    no: 90,
    location: "BEST OPTION MOTORS LIMITED",
    address: "16, OPP, IPAKODO GRAMMAR SCHOOL, IKORODU, LAGOS",
    state: "LAGOS",
  },
  {
    no: 91,
    location: "GSS/OBY TELECOMMUNICATION",
    address: "	10 LADEGBOYE,IKORODU",
    state: "LAGOS",
  },
  {
    no: 92,
    location: "	 AMALGAM STORES",
    address: "11, OMITORO STREET, IJEDE ROAD, IKORODU, LAGOS",
    state: "LAGOS",
  },
  {
    no: 93,
    location: "	MAMA CASS RESTAURANTS LIMITED (ALLEN OUTLET)",
    address: "11, ALLEN AVENUE, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 94,
    location: "PAUL IYKE VENTURES NIGERIA LIMITED",
    address: "SHOP C07, TRADE FARE, BBA, DELTA PLAZA, LAGOS STATE",
    state: "LAGOS",
  },
  {
    no: 95,
    location: "SUPO OLASUNKANMI BUNMI",
    address: "10, OLAFIKUN STREET, ODOGUNYAN, LAGOS STATE",
    state: "LAGOS",
  },
  {
    no: 96,
    location: "SUPER ROYAL INVESTMENT",
    address: "473 IKORODU ROAD, OPP KETU RETAIL MARKET, KETU",
    state: "LAGOS",
  },
  {
    no: 97,
    location: "DEPLACE ENTERPRISES",
    address: "SUITE 4 MIDWESTERN SHOPPING COMPLEX,GOLF ROAD,LAKOWE,LAGOS",
    state: "LAGOS",
  },
  {
    no: 98,
    location: "SUSSCARE ENTERPRISES",
    address: "21 OKEPOPO  ST, OPP. AGBOWA CENTRAL MOSQUE, AGBOWA, IKORODU",
    state: "LAGOS",
  },
  {
    no: 99,
    location: "	LAJIM MONUMENT ENTERPRISES",
    address: "17/19 ALLEN AVENUE, OSHOPEY PLAZA, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 100,
    location: "	IS34 ASSOCIATES LTD",
    address: "75A BODE THOMAS STREET SURULERE",
    state: "LAGOS",
  },
  {
    no: 101,
    location: "	LAURYN MAY FABRICS",
    address: "19/21 BALOGUN STREET, LAGOS ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 102,
    location: "THEO AND THEO SPORT EQUIPMENT",
    address: "5 WESTERN AVENUE, SURULERE",
    state: "LAGOS",
  },
  {
    no: 103,
    location: "100 HOURS ENTERTAINMENT ENTERPRISES",
    address: "100 AWOLOWO ROAD IKOYI LAGOS",
    state: "LAGOS",
  },
  {
    no: 104,
    location: "HILLARIOUS MAN ENTERPRISES",
    address: "112 BROAD STREET,LAGOS ISLAND",
    state: "LAGOS",
  },
  {
    no: 105,
    location: " MANDATE SHOPS AND GRILLS",
    address: "ELEVATION DRIVE, LEKKI, EPE ROAD, LAGOS",
    state: "LAGOS",
  },
  {
    no: 106,
    location: "PAX MEDICAL CENTER",
    address: "8 ONIKOYI STREET,AGUDA,SURULERE,LAGOS",
    state: "LAGOS",
  },
  {
    no: 107,
    location: "	VILLAGE KITCHEN & BAR LIMITED",
    address: "SWANHILL , NATIONAL STADIUM, LAGOS",
    state: "LAGOS",
  },
  {
    no: 108,
    location: "CHIWETALU CHRISTIAN OKOLOCHA",
    address: "	23 ROAD, G CLOSE, HOUSE 3 FESTAC",
    state: "LAGOS",
  },
  {
    no: 109,
    location: "COMELY ANCHOR AND PHARM INVEST LTD",
    address: "	11 OWOSENI STREET IJANIKIN OJO LAGOS",
    state: "LAGOS",
  },
  {
    no: 110,
    location: "	CASH N CARRY NIGERIA LIMITED/GARMENT",
    address: "51/52 MARINA LAGOS ISLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 111,
    location: "SILVER CAFE",
    address: "	2ND FLOOR E-CENTER SABO YABA LAGOS",
    state: "LAGOS",
  },
  {
    no: 112,
    location: "CUTTING EDGE PHARMACY LIMITED",
    address: "26 AJOSE STREET, MENDE, MARYLAND",
    state: "LAGOS",
  },
  {
    no: 113,
    location: "PETCARE ANIMAL HOSPITAL",
    address: "	91, OPEBI IKEJA",
    state: "LAGOS",
  },
  {
    no: 114,
    location: "	COLEMEX LIMITED",
    address: "26B BUSH STR, MENDE MARYLAND",
    state: "LAGOS",
  },
  {
    no: 115,
    location: "INES SUITES NIG LTD",
    address: "208 ROAD, D CLOSE, FESTAC.",
    state: "LAGOS",
  },
  {
    no: 116,
    location: "	MEECHEAL EXCELS LTD",
    address: "	PLT 365 AGEGE MOTOR ROAD, OPP VONO PLZ, MUSHIN",
    state: "LAGOS",
  },
  {
    no: 117,
    location: "NNANNA AUSTIN AND CO.",
    address: "	PLOT 60 IJAIYE ROAD, OGBA BUSSTOP, OGBA",
    state: "LAGOS",
  },
  {
    no: 118,
    location: "	LE LIEU DE LEILAS",
    address: "	44 OKEHO STREET, OFF IRE-AKARI ESTATE ROAD, ISOLO",
    state: "LAGOS",
  },
  {
    no: 119,
    location: "	SLIMNOTE LIMITED",
    address: "	53 SUNMOLA STREET, MEND MARYLAND, LAGOS",
    state: "LAGOS",
  },
  {
    no: 120,
    location: "ONWUKA JUSTICE OGBA",
    address: "	3 EKORO ROAD, ABULE EGBA",
    state: "LAGOS",
  },
  {
    no: 121,
    location: "ROYALTY CHRISTIAN CENTRE",
    address:
      "	1 WILLIAM ESTATE, OFF VETLAND, ABBATTOIR RIAD, OKO-OBA, ABULE EGBA",
    state: "LAGOS",
  },
  {
    no: 122,
    location: "	PARADISE GLOBAL CONCEPTS VENTS",
    address: "SHOP B 12-14 ARENA SHOPPING COMPLEX, OSHODI",
    state: "LAGOS",
  },
  {
    no: 123,
    location: "	UNODE JONAS SUNDAY",
    address: "20 PEDRO STREET,OFF DOCEMO STRET LAGOS ISLAND",
    state: "LAGOS",
  },
  {
    no: 124,
    location: "AKPAN FLORENCE",
    address: "17 OKEHO ST, DOPEMU",
    state: "LAGOS",
  },
  {
    no: 125,
    location: "GRACE AND GLORY TELECOMS",
    address: "1 IWORO AJIDO ROAD MASAFEJO,BADAGRY",
    state: "LAGOS",
  },
  {
    no: 126,
    location: "MANNERMODE GENERAL TREND LIMITED",
    address: "52,ISSAC JOHN STREET GRA. IKEJA",
    state: "LAGOS",
  },
  {
    no: 127,
    location: "UGWUAGO NWABUEZE S.",
    address: "402 ROAD JUNCTION SHOP1 OLORUNDA OYINOLA MKT FESTAC TOWN",
    state: "LAGOS",
  },
  {
    no: 128,
    location: "PREBEL SERVICES LTD",
    address: "	BLOCK 2, INOYO HAVEN ESTATE, OGOMBO ROAD, AJAH, LAGOS",
    state: "LAGOS",
  },
  {
    no: 129,
    location: "	SISSY QUEEN 4 U VENTURES",
    address: "	BLOCK 430, FLAT 1, LSDPC ESTATE, MILLE 2, LAGOS",
    state: "LAGOS",
  },
  {
    no: 130,
    location: "	EJIOFOR CHINWE JOY",
    address: "WGB BUILDING, ISHAGA ROUNDABOUT, IJU ROAD, AGEGE",
    state: "LAGOS",
  },
  {
    no: 131,
    location: "SOLA YEMI FIDELITY STORES",
    address: "	14/16 OLD OJO ROAD, MAZA MAZA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 132,
    location: "	AMENDIVINE VENTURES LIMITED",
    address: "9 TEN TEN CLOSE, BARUWA-IPAJA, ALIMOSHO",
    state: "LAGOS",
  },
  {
    no: 133,
    location: "DURU FRANCIS UCHENNE",
    address: "SHOP A 26, IBADAN LINE, IKOTUN MARKET, IKOTUN, LAGOS",
    state: "LAGOS",
  },
  {
    no: 134,
    location: "	DULWICH HOTEL AND SUITES LTD",
    address: "27, KARA STREET, OFF OSOLO WAY, AJAO ESTATE, LAGOS",
    state: "LAGOS",
  },
  {
    no: 135,
    location: "	PAULINUS CHUKWUJIEKPE OZODIUGWU",
    address: "61 ONWUKA PLAZA, IYANA OBA, OJO",
    state: "LAGOS",
  },
  {
    no: 136,
    location: "	SUNSHINE AND PARTNERS WEST AFRICA LTD",
    address: "	3, OMODIGBO STREET, MUSHIM, LAGOS",
    state: "LAGOS",
  },
  {
    no: 137,
    location: "	AUSTLUCK LIMITED ",
    address: "38, ODUDUWA WAY GRA, IKEJA, LAGOS",
    state: "LAGOS",
  },
  {
    no: 138,
    location: "MUSTAPHA OLAYINKA RAJI",
    address: "	1 MUSTAPHA ALUKO STREET,IGBE JUNCTION,IGBOGBO",
    state: "LAGOS",
  },
  {
    no: 139,
    location: "ALPHAPEACE MEDICAL CENTRE",
    address:
      "	1 CHIWUZO STREET, CANAL VIEW ESTATE, JAKANDE ESTATE, OKE-AFA, ISOLO",
    state: "LAGOS",
  },
  {
    no: 140,
    location: "	REE - DANIELLES VENTURES",
    address: "	6 EMMANUEL HIGH STREET, OJOTA",
    state: "LAGOS",
  },
  {
    no: 141,
    location: "	I. ILOCHI OKEZIE RUFUS",
    address: "ARAROMI MOSQUE, ARAROMI STREET, OSHODI MARKET, OSHODI",
    state: "LAGOS",
  },
  {
    no: 142,
    location: "TOCHUKWU EZEAFULA NOB",
    address: "	100 EGBE-ISOLO ROAD, IKOTUN-EGBE",
    state: "LAGOS",
  },
  {
    no: 143,
    location: "	OCHEGBE GLADYS ARURIWO",
    address: "	1B AGBOYI ROAD OGUDU",
    state: "LAGOS",
  },
  {
    no: 144,
    location: "	JUMEK LINKS ENTERPRISES",
    address: "	9, MODUPE OLUBUKOLA STREET, ILOGBO, OJO, LAGOS",
    state: "LAGOS",
  },
  {
    no: 145,
    location: "IKERI TOCHI SOPHIA",
    address: "19 EYIOWUAWI STREET, PEDRO SHOMOLU",
    state: "LAGOS",
  },
  {
    no: 146,
    location: "	DEMONSTRATION MINIST.WORLDWIDE INC.A C 2",
    address:
      "11/13 SIMBI STREET, OFF AGEGE MOTOR ROAD BY SHOGUNLE BUS-STOP, OSHODI, LAGOS STATE",
    state: "LAGOS",
  },
  {
    no: 147,
    location: "OLUFUNMILAYO ADETOUN BABALOLA",
    address: "10, OLABODE STREET, AJAO ESTATE, LAGOS",
    state: "LAGOS",
  },
  {
    no: 148,
    location: "	AMENDIVINE VENTURES LIMITED",
    address: "	GO YEE JUNCTION, ALIMOSHO ROAD",
    state: "LAGOS",
  },
  {
    no: 149,
    location: "DJIKPE PATIENCE E",
    address: "ITAMAGA,IKORODU",
    state: "LAGOS",
  },
  {
    no: 150,
    location: "FOMAS INTEGRATED SERVICE LIMITD",
    address: "	2, BY BOLA TINUBU MODEL M WATER BUSSTOP, IPAJA, LAGOS",
    state: "LAGOS",
  },
];
